### ISSUE TITLE
voip problems at jena

### ISSUE THREAD

**Issue by ys2206** [TheWhisp/android_device_samsung_msm7x27a-common#23] opened 2013-08-18 09:06 UTC
viber  - no sound, microphone does not work
gtalk - same as viber
skype - video does not work, sound and mic working

all this bugs works on samsung official GB

**Comment by TheWhisp** [comment] 2013-08-18 09:34
skype: works perfectly.
gtalk: perhaps upgrade to hangouts?
viber: haven't used it

**Comment by bqubique** [comment] 2013-08-18 10:20
I'm trebon user ,but Viber works perfectly ,didn't try GTalk~Hangouts ,skype : camera doesn't work

**Comment by TheWhisp** [comment] 2013-08-18 12:09
Jena and trebon doesn't have front camera. Last time I checked VOIP was working fine

**Comment by bqubique** [comment] 2013-08-18 12:25
But Skype has an option to show the back Camera ,not just the fron one

**Comment by TheWhisp** [comment] 2013-08-18 14:08
What's the point of using it?

**Comment by bqubique** [comment] 2013-08-18 15:00
personal , ?

**Comment by TheWhisp** [comment] 2013-08-18 15:55
I mean, do you take a mirror just so the other person can see you?

**Comment by ys2206** [comment] 2013-08-18 16:28
- yes, skype works perfectly but only sound and mic, back camera doesnt work on this rom. i suppose you know that arm7 can handle a video call and it its working on official GB.
- i mean google hangouts, my mistake
- viber and any other voip app doesn't work properly, except skype, believe me i have 2 of these mini's(s6500, s6500d) and i have this rom(18.7) on them. 

10 days I searching for voip app that working and i couldn't find any of them

**Comment by TheWhisp** [comment] 2013-08-18 17:20
Update to the latest build. Since back camera is nearly useless for video calling, I won't even bother fixing it. In cases like this, a logcat would useful attachment this bug report

**Comment by ys2206** [comment] 2013-08-18 20:36
-skype fully working on new build(even back camera)
-viber still does not(i was reading about this and there is couple of solutions, edit 2 lines in build prop which does not work, or modify audiorouting), seems this is a common bug with cm 10.1

logcat

https://www.dropbox.com/s/zgydnz7oh7fwpby/2013-08-18-23-10-58.txt

**Comment by pgcristyan** [comment] 2013-08-21 13:28
Well Viber actually worked perfectly on build 30.06, but since build 07.07 (the one with zRam), it got broken and it's still broken in the 18.08 build. Maybe you could check what's different regarding VoIP between 30.06 and 18.08 builds?

**Comment by TheWhisp** [comment] 2013-08-21 14:35
You can compare /etc/audio_policy.conf in both builds

**Comment by TheWhisp** [comment] 2013-08-22 17:39
The problem is that the sample rate is invalid, HAL only supports 8 and 16 khz, but audio_policy.conf allows also 44.1 and 48 khz. Try: https://www.dropbox.com/s/pfmiscwqa190vyg/audio_policy.conf Push to /system/etc/ and reboot.

**Comment by ghost** [comment] 2013-08-22 19:58
Still doesn't work.

**Comment by TheWhisp** [comment] 2013-08-22 20:18
you do know that your "still doesn't work" is completely useless? How about a logcat?

**Comment by ghost** [comment] 2013-08-22 21:50
http://pastebin.com/RAPt3963

**Comment by TheWhisp** [comment] 2013-08-23 09:16
Try: https://www.dropbox.com/s/7pfrlij4fk6ojz5/audio.primary.msm7x27a.so (with the default audio_policy.conf that came with 18/08 ROM)
Push to /system/lib/hw/ and reboot

**Comment by ghost** [comment] 2013-08-23 17:11
Works perfectly on viber, just noticed that while ringing the rear speaker is used, then it switches after the call is picked. Is this normal? [I'm still using the 18/7 build because of the Wi-Fi issue]

**Comment by TheWhisp** [comment] 2013-08-23 17:27
18/7 has routing issues. I'm marking this as fixed.

**Closed as completed** 2013-08-23 17:28 UTC
Labels: fixed
