### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by arthurvigen** [TheWhisp/android_device_samsung_msm7x27a-common#19] opened 2013-08-17 17:04 UTC
it is buggy too

Device:SGM2

**Comment by bqubique** [comment] 2013-08-17 17:28
It is working greatly on Galaxy Ace Plus with Google Maps 6.9  , so I think it only happens on latest version of Google Maps

**Comment by ghost** [comment] 2013-08-17 17:30
Happens to me on my GT-6500D

**Comment by arthurvigen** [comment] 2013-08-17 17:32
I dont think so becouse the same bug is in flash player.

Who wants to make sure instal adobe flash player for ICS+,instal swf player,download swf game and you will see that its not working

**Comment by leggiero** [comment] 2013-08-20 09:42
Same with the GT-6500

**Comment by arthur13** [comment] 2013-08-21 17:16
will it be fixed in cm10 new build?

**Comment by ghost** [comment] 2013-08-26 18:22
Happens in google maps navigation too. (Jena)

**Comment by arthur13** [comment] 2013-09-19 19:07
are there any changes?

**Comment by TheWhisp** [comment] 2013-09-19 19:23
There is no solution, either:

1) Google Apps problem ( a lot of devices have this bug, even some old high-end devices )
2) ROM uses too old APIs, but on the other hand, CM10 has official Adreno libs and CAF 3.0 kernel.

So there really is not solution and I don't know what's the cause of this.

**Comment by arthur13** [comment] 2013-09-19 19:25
ok

**Comment by TheWhisp** [comment] 2013-11-07 21:19
Fixed

**Closed as completed by TheWhisp** 2013-11-07 21:19 UTC
Labels: bug, fixed
